"""
NirvanaX — Execution Agent v2
Architecture reference: google/adk-samples/financial-advisor/execution_analyst

Key upgrades over ADK reference:
- Exact ADK EXECUTION_ANALYST_PROMPT structure (6 phases: Entry/Hold/Scale/Partial Exit/Full Exit)
- Enhanced: Indian broker context (Zerodha, Groww, HDFC Securities order types)
- Enhanced: NSE/BSE market hours, circuit breakers, T+1 settlement
- Enhanced: Live Groww price injected for specific entry level calculations
- Enhanced: SEBI position limits and margin requirements
- Enhanced: All 6 phases mandatory with detailed reasoning per ADK spec
"""

import httpx
import os
import time
from typing import Dict, Optional
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"

# ── ADK EXECUTION_ANALYST_PROMPT — exact structure, enhanced for NirvanaX ────
# Reference: financial-advisor/financial_advisor/sub_agents/execution_analyst/prompt.py
# Enhancements: Indian market specifics, live price integration, NSE/BSE context

EXECUTION_SYSTEM_PROMPT = """You are the Execution Agent in NirvanaX's institutional financial advisory system.
Architecture reference: Google ADK Financial Advisor — Execution Analyst Agent.

Objective: Generate a detailed and reasoned execution plan for the provided trading strategy.
This plan MUST be meticulously tailored to the user's risk attitude, investment period, and execution preferences.
The output must be rich in factual analysis, exploring optimal strategies and precise moments for:
entering, holding, accumulating, partially selling, and fully exiting positions.

MANDATORY: Your output MUST cover ALL SIX phases with detailed reasoning for each:

I. Foundational Execution Philosophy
   - How risk attitude + investment period + preferences shape the execution approach
   - Indian market context: NSE/BSE trading hours (9:15 AM - 3:30 PM IST), T+1 settlement,
     circuit breakers (5%/10%/20% limits), SEBI margin requirements

II. Entry Execution Strategy
   - Optimal entry conditions and timing (specific to Indian market sessions)
   - Order types: Limit, Market, Stop-Limit, AMO (After Market Orders), GTT (Good Till Triggered)
   - Position sizing using fixed fractional risk (1-2% for conservative, 2-3% for moderate, 3-5% for aggressive)
   - Initial stop-loss: ATR-based or chart-based with specific percentage levels
   - Avoid entry before major events: RBI policy dates, quarterly results, budget announcements

III. Holding & In-Trade Management
   - Monitoring frequency based on investment period
   - Dynamic stop-loss adjustments (trailing stops, breakeven moves)
   - Handling volatility: circuit breakers, earnings volatility, macro events

IV. Accumulation (Scaling-In) Strategy
   - Conditions for adding to position (trend confirmation, successful retests)
   - Sizing: Pyramid with decreasing size (50% → 30% → 20% of initial)
   - Risk recalculation after each addition

V. Partial Exit (Profit-Taking / Scaling-Out)
   - Objective triggers: 2:1 R/R, 3:1 R/R, resistance levels
   - Percentage to sell at each trigger (33% → 33% → 34%)
   - Managing remainder with trailing stop

VI. Full Exit Strategy
   - Profitable exit: trend exhaustion signals, ultimate target reached
   - Loss exit: stop-loss execution protocol (no averaging down on losses)
   - Order types for exits: Limit preferred, Market for emergency
   - Slippage minimization for Indian markets (use limit orders, avoid market open/close)

CRITICAL: Every recommendation must be substantiated with clear reasoning.
Link each recommendation to the specific trading strategy, risk attitude, and investment period.
Include specific price levels where possible using the provided live price data.
End with the mandatory legal disclaimer."""

LEGAL_DISCLAIMER = """
---
## ⚖️ Legal Disclaimer — For Educational and Informational Purposes Only

This execution plan is generated by an AI model for **educational and informational purposes only**.
It does **not** constitute financial advice. Real-world execution involves broker-specific mechanics,
live market conditions, fees, and individual circumstances not captured here.
Always consult a **qualified financial advisor** before executing any trades.
"""


async def _call_llm(prompt: str) -> str:
    if GEMINI_API_KEY:
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                resp = await client.post(
                    f"{GEMINI_URL}?key={GEMINI_API_KEY}",
                    json={
                        "contents": [{"parts": [{"text": prompt}]}],
                        "systemInstruction": {"parts": [{"text": EXECUTION_SYSTEM_PROMPT}]},
                        "generationConfig": {"maxOutputTokens": 3000, "temperature": 0.15},
                    },
                )
                if resp.status_code == 200:
                    return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
        except Exception as e:
            print(f"[ExecutionAgent/Gemini] {e}")

    if GROQ_API_KEY:
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                resp = await client.post(
                    GROQ_URL,
                    headers={"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"},
                    json={
                        "model": "llama-3.1-8b-instant",
                        "messages": [
                            {"role": "system", "content": EXECUTION_SYSTEM_PROMPT},
                            {"role": "user", "content": prompt},
                        ],
                        "max_tokens": 3000,
                        "temperature": 0.15,
                    },
                )
                if resp.status_code == 200:
                    return resp.json()["choices"][0]["message"]["content"].strip()
        except Exception as e:
            print(f"[ExecutionAgent/Groq] {e}")

    return _fallback_plan()


def _fallback_plan() -> str:
    return """# Execution Plan
*NirvanaX Execution Agent — Fallback Mode*

## I. Foundational Philosophy
Use limit orders exclusively. Risk 1-2% of capital per trade. Trade NSE during 9:15 AM - 3:30 PM IST.

## II. Entry
- Order Type: Limit order at or below current price
- Position Size: 1-2% capital risk per trade
- Stop-Loss: 5-8% below entry or below key support

## III. Holding
- Weekly review for long-term; daily for short-term
- Trail stop to breakeven after 10% gain

## IV. Scaling In
- Add only if position profitable and trend intact
- Subsequent entries: 50% of initial size

## V. Partial Exit
- Sell 33% at 2:1 R/R ratio
- Sell another 33% at 3:1 R/R ratio

## VI. Full Exit
- Stop-loss hit: exit immediately, no averaging down
- Target reached: limit order slightly below target

EXECUTION_PLAN_COMPLETE: TRUE"""


async def run_execution_agent(
    ticker: str,
    selected_strategy: str,
    market_analysis: str,
    risk_tolerance: str = "moderate",
    investment_duration: str = "long-term",
    execution_preferences: Optional[str] = None,
    live_price: Optional[float] = None,
) -> Dict:
    """
    Run the Execution Agent.

    Pipeline (ADK reference: execution_analyst_agent):
    - Takes provided_trading_strategy + user profile
    - Generates 6-phase execution plan
    - All phases mandatory per ADK EXECUTION_ANALYST_PROMPT spec
    - Enhanced with Indian market specifics and live price

    Args:
        ticker: Stock symbol
        selected_strategy: Trading strategy from Trading Analyst (ADK: provided_trading_strategy)
        market_analysis: Data Analyst report for context
        risk_tolerance: conservative | moderate | aggressive (ADK: user_risk_attitude)
        investment_duration: short-term | medium-term | long-term (ADK: user_investment_period)
        execution_preferences: Broker/order preferences (ADK: user_execution_preferences)
        live_price: Current Groww API price for specific level calculations
    """
    start = time.time()

    prefs = execution_preferences or "No specific preferences — use Indian market best practices (NSE limit orders, avoid market open/close)"
    price_context = f"\n**Current Live Price (Groww API):** ₹{live_price:,.2f}" if live_price else ""

    prompt = f"""Create a detailed 6-phase execution plan for the following:

## Instrument: {ticker.upper()}
{price_context}
## User Profile:
- Risk Attitude: {risk_tolerance}
- Investment Period: {investment_duration}
- Execution Preferences: {prefs}

## Selected Trading Strategy (provided_trading_strategy):
{selected_strategy[:2500]}

## Market Context (from Data Analyst):
{market_analysis[:1500]}

## Required Output — ALL 6 PHASES MANDATORY:

### Phase I: Foundational Execution Philosophy
Synthesize how {risk_tolerance} risk attitude + {investment_duration} period + "{prefs}" shapes execution.
Include Indian market constraints: NSE/BSE hours, T+1 settlement, circuit breakers, SEBI margins.

### Phase II: Entry Execution Strategy
- Optimal entry conditions specific to this strategy and {ticker.upper()}
- Order types: Justify choice of Limit/Market/Stop-Limit/GTT for Indian brokers
- Position sizing formula: Fixed fractional risk for {risk_tolerance} profile
  {"(Conservative: risk 1% per trade)" if risk_tolerance == "conservative" else "(Moderate: risk 1.5-2% per trade)" if risk_tolerance == "moderate" else "(Aggressive: risk 2-3% per trade)"}
- Initial stop-loss: ATR-based or chart-based with specific % level
- Timing: Avoid RBI policy dates, quarterly results, budget announcements
{f"- Specific entry levels based on live price ₹{live_price:,.2f}" if live_price else ""}

### Phase III: Holding & In-Trade Management
- Monitoring frequency for {investment_duration} horizon
- Dynamic stop-loss adjustments (trailing stops, breakeven triggers)
- Handling Indian market volatility: circuit breakers, earnings, macro events

### Phase IV: Accumulation (Scaling-In)
- Conditions for adding to {ticker.upper()} position
- Sizing: Pyramid approach (50% → 30% → 20% of initial)
- Risk recalculation after each addition
- Maximum position size limit

### Phase V: Partial Exit (Profit-Taking)
- Specific triggers: 2:1 R/R, 3:1 R/R, resistance levels
- Percentage to sell at each trigger
- Order types for partial exits
- Managing remainder position

### Phase VI: Full Exit Strategy
- Profitable exit conditions (trend exhaustion, ultimate target)
- Loss exit: stop-loss execution (no averaging down)
- Order types: Limit preferred, Market for emergency exits
- Slippage minimization for NSE/BSE

Make all recommendations specific to {ticker.upper()}, {risk_tolerance} risk, {investment_duration} horizon.
Include specific percentages, price levels, and timeframes throughout."""

    plan_text = await _call_llm(prompt)

    if "disclaimer" not in plan_text.lower():
        plan_text += LEGAL_DISCLAIMER
    if "EXECUTION_PLAN_COMPLETE" not in plan_text:
        plan_text += "\n\nEXECUTION_PLAN_COMPLETE: TRUE"

    elapsed = round(time.time() - start, 2)

    return {
        "ticker": ticker.upper(),
        "execution_plan": plan_text,
        "risk_tolerance": risk_tolerance,
        "investment_duration": investment_duration,
        "execution_preferences": prefs,
        "live_price_used": live_price,
        "plan_complete": True,
        "generated_at": datetime.utcnow().isoformat(),
        "latency_s": elapsed,
        "agent": "Execution Agent v2 (ADK-Enhanced)",
    }
