"""
NirvanaX — Trading Analyst Agent v2
Architecture reference: google/adk-samples/financial-advisor/trading_analyst

Key upgrades over ADK reference:
- Exact ADK TRADING_ANALYST_PROMPT as foundation (not just inspired by)
- Enhanced: Indian market context (NSE/BSE, SEBI, Indian tax implications)
- Enhanced: NirvanaX user financial profile integration (stress score, emergency fund)
- Enhanced: Minimum 5 strategies with mandatory diversity across market outlooks
- Enhanced: Each strategy includes Indian-specific indicators (FII/DII, RBI, NIFTY correlation)
- Enhanced: Stricter output validation and disclaimer enforcement
"""

import httpx
import os
import time
from typing import Dict, Optional
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"

# ── ADK TRADING_ANALYST_PROMPT — exact structure, enhanced for NirvanaX ──────
# Reference: financial-advisor/financial_advisor/sub_agents/trading_analyst/prompt.py
# Enhancements: Indian market context, NirvanaX profile data, stricter structure

TRADING_ANALYST_SYSTEM_PROMPT = """You are the Trading Analyst Agent in NirvanaX's institutional financial advisory system.
Architecture reference: Google ADK Financial Advisor — Trading Analyst Agent.

Overall Goal: Conceptualize and outline at least FIVE distinct trading strategies by critically evaluating
the provided market_data_analysis_output. Each strategy MUST be specifically tailored to align with the
user's stated risk attitude and intended investment period.

MANDATORY: You must develop a MINIMUM of 5 strategies. Strategies must be DIVERSE and cover different
market outlooks (bullish, bearish, neutral/range-bound) where supported by the analysis.

For EACH strategy, you MUST include ALL of the following components:
1. strategy_name: Concise, descriptive name
2. description_rationale: Why this strategy is proposed based on the market analysis + user profile
3. alignment_with_user_profile: How it aligns with risk attitude AND investment period
4. key_market_indicators_to_watch: Specific indicators from the analysis (include Indian market indicators:
   NIFTY correlation, FII/DII flows, RBI rate sensitivity, sector-specific metrics)
5. potential_entry_conditions: Specific, actionable entry triggers
6. potential_exit_conditions_or_targets: Specific profit targets and stop-loss levels
7. primary_risks_specific_to_this_strategy: Risks beyond general market risk
8. indian_tax_implications: STCG (15%, <1 year) vs LTCG (10% above ₹1L, >1 year) impact
9. estimated_return_potential: Realistic range (not guaranteed)

Strategy diversity requirements:
- At least 1 conservative/defensive strategy
- At least 1 growth/momentum strategy
- At least 1 income-generating strategy (if applicable)
- At least 1 value/fundamental strategy
- At least 1 tactical/opportunistic strategy

CRITICAL: Base strategies ONLY on the provided market analysis data. Do not fabricate market data.
If the analysis shows bearish signals, include appropriate defensive strategies.

End with the mandatory legal disclaimer.
End with: TRADING_ANALYSIS_COMPLETE: TRUE"""

LEGAL_DISCLAIMER = """
---
## ⚖️ Legal Disclaimer — For Educational and Informational Purposes Only

The trading strategies outlined above are generated by an AI model and are **for educational and informational purposes only**.
They do **not** constitute financial advice, investment recommendations, or offers to buy or sell any securities.

NirvanaX makes no representations about accuracy or completeness. **Any reliance is strictly at your own risk.**
Financial markets involve risks. Past performance is not indicative of future results.
Always consult a **qualified independent financial advisor** before making investment decisions.

*This disclaimer is mandatory per NirvanaX governance standards and Google ADK Financial Advisor architecture.*
"""


async def _call_llm(prompt: str) -> str:
    if GEMINI_API_KEY:
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                resp = await client.post(
                    f"{GEMINI_URL}?key={GEMINI_API_KEY}",
                    json={
                        "contents": [{"parts": [{"text": prompt}]}],
                        "systemInstruction": {"parts": [{"text": TRADING_ANALYST_SYSTEM_PROMPT}]},
                        "generationConfig": {"maxOutputTokens": 3000, "temperature": 0.25},
                    },
                )
                if resp.status_code == 200:
                    return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
        except Exception as e:
            print(f"[TradingAnalyst/Gemini] {e}")

    if GROQ_API_KEY:
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                resp = await client.post(
                    GROQ_URL,
                    headers={"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"},
                    json={
                        "model": "llama-3.1-8b-instant",
                        "messages": [
                            {"role": "system", "content": TRADING_ANALYST_SYSTEM_PROMPT},
                            {"role": "user", "content": prompt},
                        ],
                        "max_tokens": 3000,
                        "temperature": 0.25,
                    },
                )
                if resp.status_code == 200:
                    return resp.json()["choices"][0]["message"]["content"].strip()
        except Exception as e:
            print(f"[TradingAnalyst/Groq] {e}")

    return _fallback_strategies()


def _fallback_strategies() -> str:
    return f"""# Trading Strategy Analysis
*NirvanaX Trading Analyst Agent — Fallback Mode*
*Add GEMINI_API_KEY or GROQ_API_KEY to backend/.env for full AI analysis.*

## Strategy 1: Conservative SIP Accumulation
**Type:** Defensive Accumulation | **Risk:** Low
- Systematic monthly investment regardless of price
- Entry: Begin immediately with fixed monthly amount
- Exit: Target allocation reached or fundamental thesis changes
- Tax: LTCG applies after 1 year (10% above ₹1L)

## Strategy 2: Value Buy on Dips
**Type:** Value/Fundamental | **Risk:** Medium
- Buy during 10-15% corrections from recent highs
- Entry: Price at or below 200-day moving average
- Exit: 20-25% gain or fundamental deterioration
- Tax: STCG (15%) if held <1 year

## Strategy 3: Momentum Trend Following
**Type:** Technical/Momentum | **Risk:** Medium-High
- Follow established price trend with trailing stops
- Entry: Price above 50-day MA with increasing volume
- Exit: Trailing stop 8% below recent high
- Tax: STCG likely given shorter holding period

## Strategy 4: Dividend Income Focus
**Type:** Income Generation | **Risk:** Low-Medium
- Focus on dividend yield and payout consistency
- Entry: When dividend yield > 2% and payout ratio sustainable
- Exit: Dividend cut or yield compression below 1%
- Tax: Dividends taxed at slab rate

## Strategy 5: Sector Rotation Tactical
**Type:** Opportunistic | **Risk:** Medium
- Rotate based on RBI policy cycle and sector momentum
- Entry: Sector showing relative strength vs NIFTY
- Exit: Sector underperforms NIFTY for 2 consecutive months
- Tax: STCG/LTCG depending on holding period

{LEGAL_DISCLAIMER}

TRADING_ANALYSIS_COMPLETE: TRUE"""


async def run_trading_analyst(
    ticker: str,
    market_analysis_report: str,
    risk_tolerance: str = "moderate",
    investment_duration: str = "long-term",
    user_profile: Optional[Dict] = None,
) -> Dict:
    """
    Run the Trading Analyst Agent.

    Pipeline (ADK reference: trading_analyst_agent):
    1. Validate market_analysis_output is available (ADK: prerequisite check)
    2. Build user profile context from NirvanaX engines
    3. Generate 5+ strategies grounded in market analysis
    4. Enforce diversity across market outlooks
    5. Include Indian tax implications per strategy

    Args:
        ticker: Stock symbol
        market_analysis_report: Output from Data Analyst Agent (ADK: market_data_analysis_output)
        risk_tolerance: conservative | moderate | aggressive (ADK: user_risk_attitude)
        investment_duration: short-term | medium-term | long-term (ADK: user_investment_period)
        user_profile: NirvanaX engine outputs (stress score, emergency fund, savings rate)
    """
    # ADK prerequisite check: market analysis must be available
    if not market_analysis_report or len(market_analysis_report.strip()) < 50:
        return {
            "ticker": ticker.upper(),
            "strategies_report": (
                "⚠️ Error: Market analysis data is missing or incomplete. "
                "The Data Analyst Agent must complete its analysis before trading strategies can be generated. "
                "Please ensure Step 1 (Data Analysis) has been successfully completed."
            ),
            "error": "MISSING_MARKET_ANALYSIS",
            "analysis_complete": False,
        }

    start = time.time()

    # Build NirvanaX user profile context (enhancement over ADK)
    profile_context = ""
    if user_profile:
        profile_context = f"""
## NirvanaX User Financial Profile (Ground Truth from Deterministic Engines):
- Monthly Income: ₹{user_profile.get('monthly_income', 'N/A'):,.0f}
- Monthly Expenses: ₹{user_profile.get('monthly_expenses', 'N/A'):,.0f}
- Savings Rate: {user_profile.get('savings_rate', 'N/A')}%
- Financial Stress Score: {user_profile.get('stress_score', 'N/A')}/100
  (Score interpretation: <50 = High Stress/Defensive only, 50-75 = Moderate, >75 = Aggressive allowed)
- Emergency Fund Status: {user_profile.get('emergency_status', 'N/A')}
  (CRITICAL: If inadequate, equity/high-risk strategies must be deprioritized)

Strategy constraints from profile:
{"- Emergency fund inadequate: Prioritize capital preservation strategies. Avoid high-risk equity strategies." if user_profile.get('emergency_status') == 'inadequate' else "- Emergency fund adequate: Full strategy range available."}
{"- High stress score: Recommend defensive strategies only." if (user_profile.get('stress_score') or 100) < 50 else ""}
"""

    # Risk and duration descriptors (ADK: user_risk_attitude, user_investment_period)
    risk_map = {
        "conservative": "Conservative — capital preservation priority, maximum drawdown tolerance 10%, prefer low-volatility instruments",
        "moderate": "Moderate — balanced growth and protection, maximum drawdown tolerance 20%, accept normal market volatility",
        "aggressive": "Aggressive — maximum growth focus, drawdown tolerance >30%, willing to accept high volatility for higher returns",
    }
    duration_map = {
        "short-term": "Short-Term (<3 months) — momentum and technical setups, quick exits, STCG tax implications",
        "medium-term": "Medium-Term (3-12 months) — balance fundamentals with technicals, swing trading approach",
        "long-term": "Long-Term (>1 year) — fundamentals-driven, compounding focus, LTCG tax advantage after 1 year",
    }

    risk_desc = risk_map.get(risk_tolerance.lower(), risk_map["moderate"])
    duration_desc = duration_map.get(investment_duration.lower(), duration_map["long-term"])

    prompt = f"""Develop at least 5 distinct trading strategies for {ticker.upper()}.

## User Investment Profile:
- **Risk Attitude:** {risk_desc}
- **Investment Period:** {duration_desc}
{profile_context}

## Market Analysis Report (from Data Analyst Agent — market_data_analysis_output):
{market_analysis_report[:4000]}

## Your Task:
Based on the market analysis above and the user's profile, develop a MINIMUM of 5 diverse trading strategies.

MANDATORY strategy diversity:
1. One conservative/defensive strategy (suitable for capital preservation)
2. One growth/momentum strategy (suitable for trend following)
3. One income-generating strategy (dividends, covered calls, or yield focus)
4. One value/fundamental strategy (based on valuation metrics from the analysis)
5. One tactical/opportunistic strategy (based on specific catalysts from the analysis)

For EACH strategy, provide ALL of these components:
- **Strategy Name & Type**
- **Description & Rationale** (grounded in the market analysis data above)
- **Alignment with User Profile** (specific to {risk_tolerance} risk and {investment_duration} horizon)
- **Key Indian Market Indicators to Watch** (include NIFTY correlation, FII/DII flows, RBI sensitivity)
- **Entry Conditions** (specific, actionable triggers)
- **Exit Conditions & Targets** (specific price levels or percentage targets)
- **Stop-Loss Level** (specific percentage or technical level)
- **Primary Risks** (specific to this strategy)
- **Indian Tax Implications** (STCG 15% if <1 year, LTCG 10% above ₹1L if >1 year)
- **Estimated Return Potential** (realistic range based on analysis)

CRITICAL: Ground every strategy in the market analysis data. Reference specific findings.
If the analysis shows risks, reflect them in strategy design.
Format as professional markdown with clear section headers."""

    strategies_text = await _call_llm(prompt)

    if "disclaimer" not in strategies_text.lower():
        strategies_text += LEGAL_DISCLAIMER
    if "TRADING_ANALYSIS_COMPLETE" not in strategies_text:
        strategies_text += "\n\nTRADING_ANALYSIS_COMPLETE: TRUE"

    elapsed = round(time.time() - start, 2)

    return {
        "ticker": ticker.upper(),
        "strategies_report": strategies_text,
        "risk_tolerance": risk_tolerance,
        "investment_duration": investment_duration,
        "analysis_complete": True,
        "generated_at": datetime.utcnow().isoformat(),
        "latency_s": elapsed,
        "agent": "Trading Analyst Agent v2 (ADK-Enhanced)",
    }
